'use client';

import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        {/* Header */}
        <div className="mb-8">
          <Link href="/login" className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-500 mb-4">
            <ArrowLeft className="h-4 w-4" />
            Back to Login
          </Link>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-gray-600">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <Card className="p-8">
          <div className="prose prose-gray max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                By accessing and using Inspire AI ("the Platform"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. Description of Service</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                Inspire AI is an AI-powered influencer marketing platform that connects brands with content creators. Our services include:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2 mb-4">
                <li>AI-powered content generation and optimization</li>
                <li>Creator discovery and matching</li>
                <li>Campaign management tools</li>
                <li>Analytics and performance tracking</li>
                <li>Payment processing for campaigns</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. User Accounts</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                To access certain features of the Platform, you must create an account. You are responsible for:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2 mb-4">
                <li>Maintaining the confidentiality of your account credentials</li>
                <li>All activities that occur under your account</li>
                <li>Providing accurate and up-to-date information</li>
                <li>Notifying us immediately of any unauthorized use</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. User Conduct</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                You agree not to use the Platform to:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2 mb-4">
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe on intellectual property rights</li>
                <li>Transmit harmful or malicious content</li>
                <li>Engage in fraudulent or deceptive practices</li>
                <li>Spam or send unsolicited communications</li>
                <li>Attempt to gain unauthorized access to the Platform</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Content and Intellectual Property</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                <strong>User Content:</strong> You retain ownership of content you create and upload to the Platform. By using our services, you grant us a license to use, display, and distribute your content as necessary to provide our services.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                <strong>AI-Generated Content:</strong> Content generated by our AI tools is provided for your use but may be subject to certain restrictions. You are responsible for ensuring compliance with applicable laws and platform policies.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                <strong>Platform Content:</strong> All content, features, and functionality of the Platform are owned by Inspire AI and are protected by copyright, trademark, and other intellectual property laws.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Payment Terms</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                <strong>Fees:</strong> Some features of the Platform may require payment. All fees are non-refundable unless otherwise specified.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                <strong>Payment Processing:</strong> We use third-party payment processors. By making payments through the Platform, you agree to the terms of service of our payment processors.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                <strong>Creator Payments:</strong> Payments to creators are processed according to the terms agreed upon in individual campaign agreements.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Privacy and Data Protection</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                Your privacy is important to us. Our collection and use of personal information is governed by our Privacy Policy, which is incorporated into these Terms by reference.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Disclaimers and Limitations</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                <strong>Service Availability:</strong> We strive to maintain high service availability but do not guarantee uninterrupted access to the Platform.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                <strong>AI Content:</strong> AI-generated content is provided "as is" and may not always meet your expectations. You are responsible for reviewing and approving all AI-generated content before use.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                <strong>Limitation of Liability:</strong> To the maximum extent permitted by law, Inspire AI shall not be liable for any indirect, incidental, special, or consequential damages.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Termination</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                We may terminate or suspend your account at any time for violation of these Terms or for any other reason at our sole discretion. You may also terminate your account at any time.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">10. Changes to Terms</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                We reserve the right to modify these Terms at any time. We will notify users of significant changes via email or through the Platform. Continued use of the Platform after changes constitutes acceptance of the new Terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">11. Governing Law</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to conflict of law principles.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">12. Contact Information</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                If you have any questions about these Terms, please contact us at:
              </p>
              <div className="bg-gray-50 p-4 rounded-lg">
                <p className="text-gray-700">
                  <strong>Email:</strong> legal@inspireai.com<br />
                  <strong>Address:</strong> [Your Company Address]<br />
                  <strong>Phone:</strong> [Your Phone Number]
                </p>
              </div>
            </section>
          </div>

          <div className="mt-8 pt-6 border-t border-gray-200">
            <div className="flex flex-col sm:flex-row gap-4 justify-between items-center">
              <p className="text-sm text-gray-600">
                By using Inspire AI, you agree to these Terms of Service.
              </p>
              <div className="flex gap-3">
                <Link href="/privacy">
                  <Button variant="outline" size="sm">
                    Privacy Policy
                  </Button>
                </Link>
                <Link href="/login">
                  <Button size="sm">
                    Back to Login
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}
